#!/bin/bash

mv /tmp/nginx.conf /etc/nginx
mv /tmp/server.xml /etc/tomcat9/
mv /tmp/tomcat-users.xml /etc/tomcat9
mv /tmp/cloudwebapp-0.1.war /var/lib/tomcat9/webapps/ROOT.war
rm -r /var/lib/tomcat9/webapps/ROOT

deb-systemd-invoke stop tomcat9.service  # Stop tomcat before
useradd usr-cloud
groupadd grp-cloud
usermod -a -G grp-cloud tomcat
usermod -a -G grp-cloud usr-cloud

chown -R usr-cloud:grp-cloud /home/cloud

chown tomcat:grp-cloud /home/cloud/logs/cloud.log* || true # To prevent access denied errors on first starting tomcat
chown tomcat:tomcat /var/lib/tomcat9/webapps/ROOT.war
chmod 640 /etc/tomcat9/tomcat-users.xml
chown root:tomcat /etc/tomcat9/tomcat-users.xml
chmod 640 /etc/tomcat9/server.xml
chown root:tomcat /etc/tomcat9/server.xml
chown root:grp-cloud /etc/cloud/cacert.jks /etc/cloud/client.jks
chmod 440 /etc/cloud/cacert.jks /etc/cloud/client.jks

#A new group, grp-cloud, is added, then the users tomcat and usr-cloud added to that group.
# The grp-cloud group is then given group access to usr-cloud and it's subdirectories. The user and group permissions are then set up.

# Give directories only permission 775
find /home/cloud -type d -print0 | xargs -0 chmod 775
# Give files permission 664
find /home/cloud -type f -print0 | xargs -0 chmod 664

mv /tmp/install-cert.sh /home/cloud/
chown root:root /home/cloud/install-cert.sh

chgrp -R grp-cloud /home/cloud/
# Start the services
systemctl daemon-reload
deb-systemd-invoke enable tomcat9.service
deb-systemd-invoke start tomcat9.service
deb-systemd-invoke enable nginx.service

CERT_FILE=/etc/nginx/cloud.crt
if test -f "$CERT_FILE"; then
   deb-systemd-invoke start nginx.service
else
   deb-systemd-invoke stop nginx.service  # On initial install, the certificate won't be present so
                                          # stop
                                          # nginx as it can't work till that is set up.
   echo "To add or update the site key/certificate, run sudo install-cert.sh at www-root."
   echo "Use sudo systemctl start nginx to run nginx."
fi
