#!/bin/bash

# This will clear out the unit file refs for sc_processes service
systemctl daemon-reload
userdel usr-cloud || true
groupdel grp-cloud || true

if [ "$1" == purge ] ; then
  rm -r /var/log/tomcat10
  rm -r /var/lib/tomcat10
fi

